title: maxarvid
email: max@craftacademy.se
description: >-
  A TDD blog
  To explore webdev and more
  Fork me on Github
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
plugins:
  - jekyll-feed
include: ["_pages"]
